[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first_multi'
sort_imports = true

[profile.default]
solc_version = '0.8.29'
libs = ['node_modules', 'lib']

[rpc_endpoints]
optimism = "${OPTIMISM_RPC_URL}"
 
[etherscan]
optimism = { key = "${ETHERSCAN_API_KEY}" }